import { useEffect, useState } from "react";
import type { ApiClient } from "../api/client";
import type { UsageSummary } from "../api/types";
import type { LanguageKey } from "../components/TopNav";

interface UsagePageProps {
  api: Pick<ApiClient, "getUsageSummary">;
  language?: LanguageKey;
}

const copy = {
  "zh-CN": {
    title: "用量检测",
    subtitle: "汇总 workflow run 和 model test 产生的请求、tokens 与错误。",
    requestCount: "请求数",
    inputTokens: "输入 Tokens",
    outputTokens: "输出 Tokens",
    estimatedCost: "预估成本",
    errorCount: "错误数",
    loading: "加载中",
    summary: "运行汇总"
  },
  en: {
    title: "Usage",
    subtitle: "Summarize requests, tokens, and errors generated by workflow runs and model tests.",
    requestCount: "Requests",
    inputTokens: "Input tokens",
    outputTokens: "Output tokens",
    estimatedCost: "Estimated cost",
    errorCount: "Errors",
    loading: "Loading",
    summary: "Run summary"
  }
} satisfies Record<LanguageKey, Record<string, string>>;

const emptySummary: UsageSummary = {
  requestCount: 0,
  inputTokens: 0,
  outputTokens: 0,
  estimatedCost: 0,
  errorCount: 0
};

export function UsagePage({ api, language = "zh-CN" }: UsagePageProps) {
  const text = copy[language];
  const [summary, setSummary] = useState<UsageSummary>(emptySummary);
  const [status, setStatus] = useState(text.loading);

  useEffect(() => {
    let active = true;

    api
      .getUsageSummary()
      .then((result) => {
        if (!active) return;
        setSummary(result);
        setStatus("");
      })
      .catch((error: unknown) => {
        if (!active) return;
        setStatus(error instanceof Error ? error.message : String(error));
      });

    return () => {
      active = false;
    };
  }, [api, text.loading]);

  const metrics = [
    { label: text.requestCount, value: String(summary.requestCount), tone: "idle" },
    { label: text.inputTokens, value: String(summary.inputTokens), tone: "idle" },
    { label: text.outputTokens, value: String(summary.outputTokens), tone: "idle" },
    { label: text.errorCount, value: String(summary.errorCount), tone: summary.errorCount > 0 ? "warn" : "good" }
  ] as const;

  return (
    <main className="page">
      <div className="page-heading">
        <span className="module-badge">usage</span>
        <h1>{text.title}</h1>
        <p>{text.subtitle}</p>
      </div>

      {status && <p className="panel-status">{status}</p>}

      <section className="metric-grid" aria-label={text.summary}>
        {metrics.map((metric) => (
          <div className="metric-tile" key={metric.label}>
            <span>{metric.label}</span>
            <strong>{metric.value}</strong>
            <i className={metric.tone} />
          </div>
        ))}
      </section>

      <section className="operation-panel management-panel">
        <div className="panel-heading">
          <h2>{text.summary}</h2>
          <span>{summary.estimatedCost.toFixed(6)}</span>
        </div>
        <div className="record-list">
          <div className="record-row usage-row">
            <strong>{text.estimatedCost}</strong>
            <span>{summary.estimatedCost.toFixed(6)}</span>
            <span>USD</span>
            <em>{summary.errorCount > 0 ? "warn" : "ok"}</em>
          </div>
        </div>
      </section>
    </main>
  );
}
